### PR TITLE
Update bindgen to 0.58.

### PR DESCRIPTION
**Pull request by khuey**
Dependabot doesn't know how to rename these deprecated functions hence the build failures on its PR.

### CODE REVIEW

**Review by Phantomical — APPROVED** [review]
LGTM! Once this and my other PR are in I'll cut a 0.4 release :)

**Comment by Phantomical** [comment]
It looks like the build failures are unrelated. I think you should be good to just merge

**Comment by khuey** [comment]
I think that's https://github.com/rust-lang/rust-bindgen/issues/1651

**Comment by khuey** [comment]
poke?

**Comment by Phantomical** [comment]
Merged! Got distracted by other issues (sorry)

**Comment by khuey** [comment]
Thanks (and no worries).

**Pull request merged**
