### PR TITLE
Copyless conversion

### PR DESCRIPTION
**Pull request by tathanhdinh**
Hello all,

This is just a WIP to get your feedbacks, it changes https://github.com/rust-xed/xed-sys/blob/47d9ef7eb42c15e3c8f6c6d2935f93184de6a73e/src/c2rust.rs#L9-L10

which requires initialization (i.e. copy) by zeros, into a copyless version.

### CODE REVIEW

**Comment by Phantomical** [comment]
I was curious to see if this change would affect the generated assembly/IR. [It turns out that it doesn't][1]. In both cases the compiler is able to see through the union workarounds and implement everything directly as a bitshift+bitwise or (at least for x86_64).

I'm unsure if we want to start changing the generated c2rust code. If we start changing things here it'll make updating to a new xed version much harder if any of xed's exported inline functions change as we'll have to merge all our custom patches with the newly generated c2rust code.

As a final note. If we want to rewrite this function, wouldn't this be a better way?
```rust
pub extern "C" fn xed_make_uint64(hi: u32, lo: u32) -> u64 {
    ((hi as u64) >> 32) | (lo as u64)
}
```

[1]: https://godbolt.org/#z:OYLghAFBqd5QCxAYwPYBMCmBRdBLAF1QCcAaPECAKxAEZSAbAQwDtRiBXAZwNK9Q7FkmEAHIApAAYAggAcOAIwDUHFlyYAzTEo0slAD0zoA%2BgFsmAa0zGOeFgQBsAFmOoG6CKY4ElCCioBmACZSJS8fBlQQQKCASiUAWnEA7BVnJXEAdgAhKWklAqUGTB9wpQBPaMMTVTxUFmdjH2SAEQMjGxY6hpdmnKUFcoIRDIBWbMlk7KUADnFRtqyWqbzCioA6LnXI4IyAtsiVmTXyzfW/XdbfPCP8wuISwT1T4nEggI5nW6W8vO5tHjoEAgUyYUzArLZACyTHKCkwAFUul0CD8ArkZPJlLp2iZzFYbHZHC4WJgAO6ebzXaIcYKhMqRGnBeJJFJpJwZHKrQrFUpU8p7NowuGI5GECEBADC1U63UaqJSwNqKIgsVua15SlkBGIgo2TC4Zm8xm1xFVSgNSgAVGUZbV6vKLVxrWVaUF1YVVOotJyMXc1gVTesycRCJgIJE1ejuQGtTr1kx0B5aLFg6HhhA/FG/bGChArRBTgaTTrVbFU693p8nDHOcsZD8G03pG8AvNsg9ZGbJWqFr93u2sKGAG7hyWoWTlUKSyKk3v1uSKFRdeq42UO3q%2B2tYgZDEbt4GA4GoLjA4hMMnA5A2ZAIJivdGzbh4ABemHmLVI26XZJIQLG2SHgQQIgCeZ4XleNhcAgJAKtMTjPm%2BH5fschQ7ugv7EP%2BB4gEeoGniA56XighL2FMShBIh74LCh/pakuhqDMM0Q4XhYGERBJG3ve5EzFRyHfsohqYdh4xASB7FEZB0GweRCFcK%2B1GfoJSiGhhf4sWJuHAceBFSSRRLkZRClITRKkKFUHT2j0TTGMYCh2OgwCYCwTTlMY9AqZea7WfKdkOSwTkuW5xghCpp4%2BSuNkEP5jnOa5BDuQEtFrDu1bROJungcR14cLOwD5SlaFLngzgZdpEl6Zx175YVtb2XFwXWcYTAMHgwAsDSzi0Y2LYNgO4ydt2879m24xDngo4QOOk7TrOmAjZiDE6hwyA%2BHaUV%2BQ1gXxSFtBbqhgZLgokjlWxVU5Ted5kOZtBnTp%2BHZZBq3XUVR3KAoQT3ZVT0kS995vfRH0BN9WUcZd/03YdQMDE4oOPeDz3cVDdE7goozw5J1VXQD5kOJjF1I695mZATv25cjPWZAuo3tkN02LS2A3ZBNU0zVOSgzvUC0fnkO48Jwa2RXKvSxTtwWJaFB2oz%2Bp1KJlCP6blMnELwXl3fLFVg0rUEwargM7mSX2a%2Bd5O67BBs/iDJsPVjEMq2rDbU78/VjR2mBdgzvOu4OmAjmOE4c1zc7e4uQkrULG0i7Z21BQlSXS6lS47MbCt289RKW8oFyp1rivY7Y9hUwuoixIwYijKIpCdaIkhV1EogAErcD4/CCMIGTvLQVcEGIdflqQFggKMkjrKMmS0AAnJPQRBA4k8j0Ek8zKM5eiE4Vc13XpAN1Xp6SKQve16XpBwLASBoKYsh4MUZAUBAl/X7fIBdMACAEAwU4aDfwzEKeEAWWPqQAK95KiiG7qQS%2BoJ7AAHkWCfz7lXLA5g2DFEQaQfADw1qTUwKeIBmBDDIG8CIcBVciSYAYOgtqChzzEHKOOLAYgIE6jwOCUhZdmBsEIi3RgeAFCnkgGXCcBBuh4ISJKJQwiEjFFHAwVoAREgSIYEQVoGgmAED3gIIQIgUxr0rtXdBDdOA8GQEoV%2B79P5KAgLgQgJBO4BHoJzVAV8b5%2B3sSmJQzceA90QWXTMIAiBuHIJQe8wA8FV0fq44gdBSBGFsdE%2BggSGAAEkgQMAYMOUwCRTDIHUZwFgFhSAhiYLIJhJ9KGiH0VveuYh0mZOybk9xSgySEAQEoYxBBTHmI/uUHxx8B5DycJPdYTgggzEkJITImQAiSCGZkSQyUKkbwMUA3efAQAHyPv3DhYggib0MWIPp2zSCjj/t0EATggA%3D

**Comment by tathanhdinh** [comment]
@unterkontrolle Thank you.

Yeah, this case is too trivial to get any benefit of copyless. The LLVM can easily recognize the dead store by initialization by zero and eliminate this.

Comparing generated machine code will not help: if we want a fastest possible conversion in this case, it would better to manually code it in assembly.

The WIP presents rather an idea where we can profit `MaybeUninit` to reduce any "non-natural" initialization by zero (the question here is why zero but not one, or two, or something else?).

Since Rust 1.36, `mem::uninitialized` is not recommended since it's too difficult to use it correctly.

I will close the PR? or you need we discuss more?

**Comment by unterkontrolle** [comment]
> The WIP presents rather an idea where we may profit `MaybeUninit` to reduce any "non-natural" initialization by zero (the question here is why zero but not one, or two, or something else?).

I like this. Maybe we can create a feature request in c2rust's repository?

**Comment by unterkontrolle** [comment]
> There are another quesions, why this function is marked as `unsafe`?, is Rust type punning by union safe? And why isn't your version used?
> 
> ```rust
> pub extern "C" fn xed_make_uint64(hi: u32, lo: u32) -> u64 {
>     ((hi as u64) >> 32) | (lo as u64)
> }
> ```
> 
> it's short and correct.

I think it's due to the `extern "C"` part. The function doesn't need it because it doesn't call a function inside the XED C library.

**Pull request closed without merging**
